#!/bin/bash
# =============================================================================
# EVIDENCIA PRÁCTICA 04 — Criterio 5 (15 pts)
# Comparación específica entre S3 y servidor EC2 (Práctica 3)
# =============================================================================

echo "=============================================="
echo "  P04 · Criterio 5: Comparación S3 vs EC2"
echo "=============================================="
echo ""
echo "┌─────────────────────────┬──────────────────────────┬──────────────────────────────┐"
echo "│ Aspecto                 │ Práctica 3 — EC2 + Nginx │ Práctica 4 — S3 estático     │"
echo "├─────────────────────────┼──────────────────────────┼──────────────────────────────┤"
echo "│ Lo que administramos    │ Instancia EC2, Nginx,     │ Solo archivos y política.    │"
echo "│                         │ sistema operativo,        │ S3 es totalmente gestionado. │"
echo "│                         │ actualizaciones de SO,    │ Sin SO, sin procesos,        │"
echo "│                         │ PM2, logs del servidor.   │ sin parches de seguridad.    │"
echo "├─────────────────────────┼──────────────────────────┼──────────────────────────────┤"
echo "│ Con 1000 usuarios       │ La instancia t3.micro     │ S3 escala automáticamente    │"
echo "│ simultáneos             │ puede saturarse (CPU,     │ sin configuración. AWS       │"
echo "│                         │ memoria, conexiones).     │ distribuye las peticiones    │"
echo "│                         │ Necesitaríamos escalar    │ en infraestructura global.   │"
echo "│                         │ manualmente o poner un    │ No hay servidor que saturar. │"
echo "│                         │ Load Balancer.            │                              │"
echo "├─────────────────────────┼──────────────────────────┼──────────────────────────────┤"
echo "│ Disponibilidad          │ Si EC2 cae, el sitio cae. │ SLA de AWS S3: 99.99%.       │"
echo "│                         │ Hay que monitorear y      │ Redundancia multi-AZ         │"
echo "│                         │ reiniciar.                │ incorporada.                 │"
echo "├─────────────────────────┼──────────────────────────┼──────────────────────────────┤"
echo "│ Costo por la página     │ EC2 t3.micro: ~\$0.0104/h  │ S3: ~\$0.000023 por GB/mes.  │"
echo "│ informativa             │ = ~\$7.50/mes solo para    │ Con < 1 MB de archivos:      │"
echo "│                         │ tener el servidor         │ < \$0.01/mes en total.        │"
echo "│                         │ encendido.                │                              │"
echo "└─────────────────────────┴──────────────────────────┴──────────────────────────────┘"
echo ""
echo "CONCLUSIÓN:"
echo "  El servidor EC2 es necesario para la API REST y la lógica del negocio"
echo "  (consultas a la base de datos, autenticación, cálculo de reportes)."
echo "  Pero para contenido que no varía por usuario — como esta página —"
echo "  usar EC2 desperdicia cómputo y eleva el costo sin beneficio real."
echo "  La separación estático/dinámico es una práctica de arquitectura estándar:"
echo "  S3 sirve lo que no cambia, EC2 procesa lo que sí cambia."
